(ns scrabble.assets
  (:require-macros [scrabble.assets :refer [slurp-b64]]))


(def b64-tiles
  {:A (slurp-b64 "resources/public/img/A.png")
   :B (slurp-b64 "resources/public/img/B.png")
   :C (slurp-b64 "resources/public/img/C.png")
   :D (slurp-b64 "resources/public/img/D.png")
   :E (slurp-b64 "resources/public/img/E.png")
   :F (slurp-b64 "resources/public/img/F.png")
   :G (slurp-b64 "resources/public/img/G.png")
   :H (slurp-b64 "resources/public/img/H.png")
   :I (slurp-b64 "resources/public/img/I.png")
   :J (slurp-b64 "resources/public/img/J.png")
   :K (slurp-b64 "resources/public/img/K.png")
   :L (slurp-b64 "resources/public/img/L.png")
   :M (slurp-b64 "resources/public/img/M.png")
   :N (slurp-b64 "resources/public/img/N.png")
   :O (slurp-b64 "resources/public/img/O.png")
   :P (slurp-b64 "resources/public/img/P.png")
   :Q (slurp-b64 "resources/public/img/Q.png")
   :R (slurp-b64 "resources/public/img/R.png")
   :S (slurp-b64 "resources/public/img/S.png")
   :T (slurp-b64 "resources/public/img/T.png")
   :U (slurp-b64 "resources/public/img/U.png")
   :V (slurp-b64 "resources/public/img/V.png")
   :W (slurp-b64 "resources/public/img/W.png")
   :X (slurp-b64 "resources/public/img/X.png")
   :Y (slurp-b64 "resources/public/img/Y.png")
   :Z (slurp-b64 "resources/public/img/Z.png")
   })
